Rename macro length to sw_length to avoid conflicts with <gmock.h>
gmock/gmock-matchers.h:578:21: error: expected unqualified-id
  578 |   return (type_name.length() <= 20 ||
      |                     ^
./tests/gtests/sw_testhelpers.h:17:23: note: expanded from macro 'length'
   17 | #define length(array) (sizeof(array) / sizeof(*(array)))
      |                       ^