Ignore NULL pointer dereferencing errors from Clang Tidy
error: Array access (from variable 'sendInputs') results in a null pointer dereference
error: Array access (from variable 'counts') results in a null pointer dereference

- These errors are to be ignored because in the reports (see below, slightly modified to save space), Tidy assumes a path of execution we do not allow
	* I.e., assuming `if (SW_MPI_setup_fail(LogInfo->stopRun, MPI_COMM_WORLD))` will not exit early if the flag `stopRun` is set

```
SOILWAT2/src/SW_MPI.c:2476:13: note: Assuming field 'stopRun' is not equal to 0
 2476 |         if (LogInfo->stopRun) {
      |             ^~~~~~~~~~~~~~~~
SOILWAT2/src/SW_MPI.c:2476:9: note: Taking true branch
 2476 |         if (LogInfo->stopRun) {
      |         ^
SOILWAT2/src/SW_MPI.c:2477:13: note: Returning without writing to '*counts'
 2477 |             return;
      |             ^
SOILWAT2/src/SW_MPI.c:6146:5: note: Returning from 'alloc_IO_info'
 6146 |     alloc_IO_info(
		...
      |         ~~~~~~~~~~~
SOILWAT2/src/SW_MPI.c:6165:18: note: Field 'stopRun' is not equal to 0
 6165 |     if (LogInfo->stopRun) {
      |                  ^
SOILWAT2/src/SW_MPI.c:6165:5: note: Taking true branch
 6165 |     if (LogInfo->stopRun) {
      |     ^
SOILWAT2/src/SW_MPI.c:6166:9: note: Control jumps to line 6203
 6166 |         goto checkStatus;
      |         ^
SOILWAT2/src/SW_MPI.c:6203:5: note: Taking false branch
 6203 |     if (SW_MPI_setup_fail(LogInfo->stopRun, MPI_COMM_WORLD)) {
```