Address compiling warning in `googletest` converted into error on certain setups
- address issue #206:
```
In file included from googletest/googletest/src/gtest-all.cc:42:
googletest/googletest/src/gtest.cc:393:12: error: missing field 'owner_' initializer [-Werror,-Wmissing-field-initializers]
GTEST_API_ GTEST_DEFINE_STATIC_MUTEX_(g_linked_ptr_mutex);
```
- this appears to be a problem described here https://github.com/google/googletest/issues/1521 which remains unsolved as of today

- another project on github addressed this issue temporarily (https://github.com/advancedtelematic/aktualizr/pull/841) by checking out `googletest` one commit before this problem was introduced with commit google/googletest@87a4cdd, i.e, https://github.com/google/googletest/commit/7888184f28509dba839e3683409443e0b5bb8948