Renamed swprintf to sw_printf to avoid name conflict with <wchar.h>
wchar.h:115:5: error: conflicting types for 'printf'
  115 | int     swprintf(wchar_t * __restrict, size_t, const wchar_t * __restrict, ...);
      |         ^
./include/generic.h:151:18: note: expanded from macro 'swprintf'
  151 | #define swprintf printf
      |                  ^
stdio.h:167:6: note: previous declaration is here
  167 | int      printf(const char * __restrict, ...) __printflike(1, 2);