Fix `snprintf()` error on Linux
- Error
	* src/SW_MPI.c:2083:18: error: ‘_’ directive output may be truncated writing 1 byte into a region of size between 0 and 511 [-Werror=format-truncation=]

- Swap size of "logBuffer" to LARGE_VALUE (1024) from MAX_FILENAMESIZE (512)
- Use "sizeof()" instead of constant within `snprintf()`