Removed unused macro "abs" to avoid conflict with <stdlib.h>
stdlib.h:132:10: error: expected identifier or '('
  132 | int      abs(int) __pure2;
      |              ^
stdlib.h:132:10: error: expected ')'
stdlib.h:132:6: note: to match this '('
  132 | int      abs(int) __pure2;
      |          ^
./include/generic.h:106:18: note: expanded from macro 'abs'
  106 | #define abs(a) (((a) < 0) ? (-a) : (a))
      |                  ^