makefile: add gtest library to LDIBS instead of listing as input file
- travis-ci (both clang and g++) and appveyor-ci error out during `make
test` with warnings such as "undefined reference to
testing::InitGoogleTest(int*, char**)'"

- maybe this is because the google test library is not correctly
linked? --> attempt to fix this by adding `-l$(gtest)` instead of
$(lib_gtest)